### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../model/default.pt'

### ISSUE THREAD

**Issue by HinamonAmu** [hehh77/3DGT-DDI#1]
Hello, when I run your code, I get the following error: " _No such file or directory: '../model/default.pt_'",I think it's because the model folder is missing. 
In your readme.md, you mentioned that there are 3 files, but I only saw the datasets file. Can you provide the model and the runs folders? Thanks and best regards.

**Comment by hehh77** [comment]
Thank you for your question. You can try to create an empty model folder.
